# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dragon/Documents/Dev/IIT_Fits

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dragon/Documents/Dev/IIT_Fits

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dragon/Documents/Dev/IIT_Fits/CMakeFiles /Users/dragon/Documents/Dev/IIT_Fits//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dragon/Documents/Dev/IIT_Fits/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GlobalAnalysis

# Build rule for target.
GlobalAnalysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GlobalAnalysis
.PHONY : GlobalAnalysis

# fast build rule for target.
GlobalAnalysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/build
.PHONY : GlobalAnalysis/fast

src/GlobalAnalyzer.o: src/GlobalAnalyzer.cc.o
.PHONY : src/GlobalAnalyzer.o

# target to build an object file
src/GlobalAnalyzer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/GlobalAnalyzer.cc.o
.PHONY : src/GlobalAnalyzer.cc.o

src/GlobalAnalyzer.i: src/GlobalAnalyzer.cc.i
.PHONY : src/GlobalAnalyzer.i

# target to preprocess a source file
src/GlobalAnalyzer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/GlobalAnalyzer.cc.i
.PHONY : src/GlobalAnalyzer.cc.i

src/GlobalAnalyzer.s: src/GlobalAnalyzer.cc.s
.PHONY : src/GlobalAnalyzer.s

# target to generate assembly for a file
src/GlobalAnalyzer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/GlobalAnalyzer.cc.s
.PHONY : src/GlobalAnalyzer.cc.s

src/StyleFile.o: src/StyleFile.cc.o
.PHONY : src/StyleFile.o

# target to build an object file
src/StyleFile.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/StyleFile.cc.o
.PHONY : src/StyleFile.cc.o

src/StyleFile.i: src/StyleFile.cc.i
.PHONY : src/StyleFile.i

# target to preprocess a source file
src/StyleFile.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/StyleFile.cc.i
.PHONY : src/StyleFile.cc.i

src/StyleFile.s: src/StyleFile.cc.s
.PHONY : src/StyleFile.s

# target to generate assembly for a file
src/StyleFile.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/StyleFile.cc.s
.PHONY : src/StyleFile.cc.s

src/TCFGExtractor.o: src/TCFGExtractor.cc.o
.PHONY : src/TCFGExtractor.o

# target to build an object file
src/TCFGExtractor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/TCFGExtractor.cc.o
.PHONY : src/TCFGExtractor.cc.o

src/TCFGExtractor.i: src/TCFGExtractor.cc.i
.PHONY : src/TCFGExtractor.i

# target to preprocess a source file
src/TCFGExtractor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/TCFGExtractor.cc.i
.PHONY : src/TCFGExtractor.cc.i

src/TCFGExtractor.s: src/TCFGExtractor.cc.s
.PHONY : src/TCFGExtractor.s

# target to generate assembly for a file
src/TCFGExtractor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/TCFGExtractor.cc.s
.PHONY : src/TCFGExtractor.cc.s

src/TCFGInterface.o: src/TCFGInterface.cc.o
.PHONY : src/TCFGInterface.o

# target to build an object file
src/TCFGInterface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/TCFGInterface.cc.o
.PHONY : src/TCFGInterface.cc.o

src/TCFGInterface.i: src/TCFGInterface.cc.i
.PHONY : src/TCFGInterface.i

# target to preprocess a source file
src/TCFGInterface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/TCFGInterface.cc.i
.PHONY : src/TCFGInterface.cc.i

src/TCFGInterface.s: src/TCFGInterface.cc.s
.PHONY : src/TCFGInterface.s

# target to generate assembly for a file
src/TCFGInterface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlobalAnalysis.dir/build.make CMakeFiles/GlobalAnalysis.dir/src/TCFGInterface.cc.s
.PHONY : src/TCFGInterface.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GlobalAnalysis"
	@echo "... src/GlobalAnalyzer.o"
	@echo "... src/GlobalAnalyzer.i"
	@echo "... src/GlobalAnalyzer.s"
	@echo "... src/StyleFile.o"
	@echo "... src/StyleFile.i"
	@echo "... src/StyleFile.s"
	@echo "... src/TCFGExtractor.o"
	@echo "... src/TCFGExtractor.i"
	@echo "... src/TCFGExtractor.s"
	@echo "... src/TCFGInterface.o"
	@echo "... src/TCFGInterface.i"
	@echo "... src/TCFGInterface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

